import { defineField, defineType } from "sanity";

const directionFieldsets = [
  { name: "directionHero", title: "Bannière (hero)", options: { collapsible: true } },
  { name: "directionHistory", title: "Section Histoire", options: { collapsible: true } },
  {
    name: "directionMissionVision",
    title: "Mission & Vision",
    options: { collapsible: true },
  },
  { name: "directionIdentity", title: "Bloc identité", options: { collapsible: true } },
  { name: "directionValues", title: "Section Valeurs", options: { collapsible: true } },
  { name: "directionAbout", title: "Présentation détaillée", options: { collapsible: true } },
  { name: "directionCta", title: "Appel à action (bas de page)", options: { collapsible: true } },
] as const;

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Paramètres du site",
  type: "document",
  groups: [
    { name: "general", title: "Général", default: true },
    { name: "direction", title: "Page — La Direction" },
    { name: "schools", title: "Page — Nos Écoles" },
    { name: "news", title: "Page — Actualités" },
    { name: "contact", title: "Page — Contact" },
  ],
  fieldsets: [...directionFieldsets],
  fields: [
    defineField({
      name: "fullName",
      title: "Nom complet officiel (référence)",
      type: "string",
      group: "general",
      description: "Nom légal complet. Peut être repris dans la bannière Direction si besoin.",
      initialValue:
        "La Direction des Écoles Chrétiennes des Assemblées de Dieu pour l'Éducation au Sénégal",
    }),
    defineField({
      name: "tagline",
      title: "Slogan (pied de page)",
      type: "string",
      group: "general",
    }),
    defineField({
      name: "acronymMeaning",
      title: "Signification de DECADES",
      type: "text",
      rows: 2,
      group: "direction",
      fieldset: "directionHistory",
      initialValue:
        "l'acronyme du nom officiel : Direction, Écoles, Chrétiennes, Assemblées, Dieu, Éducation, Sénégal.",
    }),

    /* —— Page La Direction —— */
    defineField({
      name: "directionHeroLabel",
      title: "Sur-titre (petit texte orange)",
      type: "string",
      group: "direction",
      fieldset: "directionHero",
      initialValue: "Qui sommes-nous",
    }),
    defineField({
      name: "directionHeroTitle",
      title: "Titre principal",
      type: "string",
      group: "direction",
      fieldset: "directionHero",
      initialValue: "LA DECADES",
    }),
    defineField({
      name: "directionHeroDescription",
      title: "Texte sous le titre",
      type: "text",
      rows: 4,
      group: "direction",
      fieldset: "directionHero",
      description: "Souvent le nom officiel complet ou une accroche courte.",
    }),
    defineField({
      name: "directionHeroImage",
      title: "Image de fond",
      type: "image",
      group: "direction",
      fieldset: "directionHero",
      options: { hotspot: true },
    }),

    defineField({
      name: "historySectionLabel",
      title: "Libellé de section (petit titre)",
      type: "string",
      group: "direction",
      fieldset: "directionHistory",
      initialValue: "Histoire",
    }),
    defineField({
      name: "historyTitle",
      title: "Titre de la section",
      type: "string",
      group: "direction",
      fieldset: "directionHistory",
      initialValue: "L'histoire de LA DECADES",
    }),
    defineField({
      name: "historyIntro",
      title: "Texte d'introduction",
      type: "text",
      rows: 6,
      group: "direction",
      fieldset: "directionHistory",
    }),
    defineField({
      name: "history",
      title: "Texte détaillé (paragraphes)",
      type: "array",
      of: [{ type: "block" }],
      group: "direction",
      fieldset: "directionHistory",
    }),
    defineField({
      name: "historyImage",
      title: "Photo",
      type: "image",
      group: "direction",
      fieldset: "directionHistory",
      options: { hotspot: true },
    }),
    defineField({
      name: "historyImageCaption",
      title: "Légende si pas de photo",
      type: "string",
      group: "direction",
      fieldset: "directionHistory",
      initialValue: "Une histoire au service de l'éducation",
    }),
    defineField({
      name: "foundedYear",
      title: "Année de fondation",
      type: "string",
      group: "direction",
      fieldset: "directionHistory",
      description: "Ex. 1998",
    }),

    defineField({
      name: "missionSectionLabel",
      title: "Mission — libellé",
      type: "string",
      group: "direction",
      fieldset: "directionMissionVision",
      initialValue: "Mission",
    }),
    defineField({
      name: "missionSectionTitle",
      title: "Mission — titre",
      type: "string",
      group: "direction",
      fieldset: "directionMissionVision",
      initialValue: "Notre mission",
    }),
    defineField({
      name: "mission",
      title: "Mission — texte",
      type: "text",
      rows: 5,
      group: "direction",
      fieldset: "directionMissionVision",
    }),
    defineField({
      name: "visionSectionLabel",
      title: "Vision — libellé",
      type: "string",
      group: "direction",
      fieldset: "directionMissionVision",
      initialValue: "Vision",
    }),
    defineField({
      name: "visionSectionTitle",
      title: "Vision — titre",
      type: "string",
      group: "direction",
      fieldset: "directionMissionVision",
      initialValue: "Notre vision",
    }),
    defineField({
      name: "vision",
      title: "Vision — texte",
      type: "text",
      rows: 5,
      group: "direction",
      fieldset: "directionMissionVision",
    }),

    defineField({
      name: "identitySectionLabel",
      title: "Libellé",
      type: "string",
      group: "direction",
      fieldset: "directionIdentity",
      initialValue: "Notre identité",
    }),
    defineField({
      name: "identitySectionTitle",
      title: "Titre",
      type: "string",
      group: "direction",
      fieldset: "directionIdentity",
      initialValue: "Un réseau d'écoles chrétiennes",
    }),
    defineField({
      name: "identityDescription",
      title: "Description",
      type: "text",
      rows: 4,
      group: "direction",
      fieldset: "directionIdentity",
    }),
    defineField({
      name: "identityQuote",
      title: "Citation (encadré)",
      type: "text",
      rows: 3,
      group: "direction",
      fieldset: "directionIdentity",
    }),
    defineField({
      name: "identityButtonLabel",
      title: "Texte du bouton",
      type: "string",
      group: "direction",
      fieldset: "directionIdentity",
      initialValue: "Découvrir nos écoles",
    }),
    defineField({
      name: "identityButtonHref",
      title: "Lien du bouton",
      type: "string",
      group: "direction",
      fieldset: "directionIdentity",
      initialValue: "/ecoles",
    }),

    defineField({
      name: "valuesSectionLabel",
      title: "Libellé",
      type: "string",
      group: "direction",
      fieldset: "directionValues",
      initialValue: "Valeurs",
    }),
    defineField({
      name: "valuesSectionTitle",
      title: "Titre",
      type: "string",
      group: "direction",
      fieldset: "directionValues",
      initialValue: "Ce qui nous guide au quotidien",
    }),
    defineField({
      name: "valuesSectionDescription",
      title: "Description",
      type: "text",
      rows: 2,
      group: "direction",
      fieldset: "directionValues",
    }),
    defineField({
      name: "values",
      title: "Liste des valeurs",
      type: "array",
      of: [{ type: "string" }],
      group: "direction",
      fieldset: "directionValues",
      options: { layout: "tags" },
    }),

    defineField({
      name: "aboutSectionLabel",
      title: "Libellé",
      type: "string",
      group: "direction",
      fieldset: "directionAbout",
      initialValue: "Présentation",
    }),
    defineField({
      name: "aboutSectionTitle",
      title: "Titre",
      type: "string",
      group: "direction",
      fieldset: "directionAbout",
      initialValue: "La direction en détail",
    }),
    defineField({
      name: "about",
      title: "Contenu (texte riche)",
      type: "array",
      of: [{ type: "block" }],
      group: "direction",
      fieldset: "directionAbout",
    }),

    defineField({
      name: "directionCtaTitle",
      title: "Titre",
      type: "string",
      group: "direction",
      fieldset: "directionCta",
      initialValue: "Rejoignez la communauté LA DECADES",
    }),
    defineField({
      name: "directionCtaDescription",
      title: "Description",
      type: "text",
      rows: 3,
      group: "direction",
      fieldset: "directionCta",
    }),
    defineField({
      name: "directionCtaPrimaryLabel",
      title: "Bouton principal — texte",
      type: "string",
      group: "direction",
      fieldset: "directionCta",
      initialValue: "Nous contacter",
    }),
    defineField({
      name: "directionCtaPrimaryHref",
      title: "Bouton principal — lien",
      type: "string",
      group: "direction",
      fieldset: "directionCta",
      initialValue: "/contact",
    }),
    defineField({
      name: "directionCtaSecondaryLabel",
      title: "Bouton secondaire — texte",
      type: "string",
      group: "direction",
      fieldset: "directionCta",
      initialValue: "Nos actualités",
    }),
    defineField({
      name: "directionCtaSecondaryHref",
      title: "Bouton secondaire — lien",
      type: "string",
      group: "direction",
      fieldset: "directionCta",
      initialValue: "/actualites",
    }),

    /* —— Page Nos Écoles —— */
    defineField({
      name: "schoolsHeroImage",
      title: "Image bannière (hero)",
      type: "image",
      group: "schools",
      options: { hotspot: true },
    }),
    defineField({
      name: "schoolsIntro",
      title: "Texte d'introduction",
      type: "text",
      rows: 4,
      group: "schools",
    }),

    /* —— Page Actualités —— */
    defineField({
      name: "newsHeroImage",
      title: "Image bannière (hero)",
      type: "image",
      group: "news",
      options: { hotspot: true },
    }),
    defineField({
      name: "newsIntro",
      title: "Texte d'introduction",
      type: "text",
      rows: 4,
      group: "news",
    }),

    /* —— Page Contact —— */
    defineField({
      name: "contactHeroImage",
      title: "Image bannière (hero)",
      type: "image",
      group: "contact",
      options: { hotspot: true },
    }),
    defineField({
      name: "contactIntro",
      title: "Texte d'introduction",
      type: "text",
      rows: 3,
      group: "contact",
    }),
    defineField({
      name: "contactEmail",
      title: "E-mail",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "contactPhone",
      title: "Téléphone",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "contactAddress",
      title: "Adresse du siège",
      type: "string",
      group: "contact",
      description: "Affichée sur la page Contact et utilisée pour la carte si les coordonnées GPS ne sont pas renseignées.",
    }),
    defineField({
      name: "contactMapLat",
      title: "Carte — latitude (optionnel)",
      type: "number",
      group: "contact",
      description: "Ex. 14.7167 pour Dakar. Plus précis que l’adresse seule.",
    }),
    defineField({
      name: "contactMapLng",
      title: "Carte — longitude (optionnel)",
      type: "number",
      group: "contact",
      description: "Ex. -17.4677 pour Dakar.",
    }),
    defineField({
      name: "contactMapZoom",
      title: "Carte — niveau de zoom",
      type: "number",
      group: "contact",
      initialValue: 15,
      validation: (rule) => rule.min(10).max(20),
    }),
  ],
  preview: {
    prepare() {
      return { title: "Paramètres du site — LA DECADES" };
    },
  },
});
